const express = require("express")
const router = express.Router()
const userController = require("../controller/admin/userController")
router.get("/create",userController.create)
router.post("/create",userController.postcreate)
router.get("/update/:iduser",userController.update)
router.post("/update/:iduser",userController.postupdate)
router.get("/del/:iduser",userController.getDel)
// router.delete("/del/:iduser",userController.getDel)
router.get("/reset/:iduser",userController.reset)
router.post("/reset/:iduser",userController.postResetPassword)
module.exports = router
